const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { randomBytes } = require('node:crypto');
const { _electron } = require('playwright');

(async () => {
  const executable = process.argv[2];
  if (!executable) throw new Error('Pass the unpacked Electron executable');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'packaged-worker-'));
  const config = path.join(root, 'worker.json');
  const { createService } = await import('../src/server.mjs');
  const { api } = await import('../src/worker.mjs');
  const { WorkerManager } = await import('../desktop/manager.mjs');
  const key = randomBytes(36).toString('hex');
  const service = createService({ dataDir: path.join(root, 'server'), masterKey: key });
  await new Promise(resolve => service.server.listen(0, '127.0.0.1', resolve));
  const server = `http://127.0.0.1:${service.server.address().port}`;
  const owner = { server, ...await api({ server }, '/api/pair', 'POST', { key, name: 'packaged-test-owner' }) };
  const pairing = await api(owner, '/api/pairings', 'POST', { role: 'worker' });
  const agent = path.resolve(__dirname, '../test/fixtures/fake-agent.mjs');
  fs.writeFileSync(config, JSON.stringify({ dataDir: path.join(root, 'data'), server, pollMs: 250,
    capabilities: ['article'], agents: { codex: { command: process.execPath, args: [agent], versionArgs: [agent, '--version'] } } }));
  const env = { ...process.env, COLLECTOR_CONFIG: config, COLLECTOR_DESKTOP_TEST: '1', COLLECTOR_DESKTOP_STORAGE_FIXTURE: '1' };
  delete env.ELECTRON_RUN_AS_NODE;
  const app = await _electron.launch({ executablePath: path.resolve(executable), env });
  const manager = new WorkerManager(config, process.execPath);
  const until = async fn => { for (let i = 0; i < 200; i++) { if (await fn()) return; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Packaged Worker timeout'); };
  try {
    await app.firstWindow();
    const page = app.windows().find(window => !window.url().includes('compact=1'));
    assert.ok(page, 'Main Worker window missing');
    await page.locator('[data-view=worker]').click();
    await page.locator('#pair-worker').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-action=start]').isDisabled(), true);
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.locator('#theme-toggle').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
    assert.equal(await page.locator('#theme-toggle').getAttribute('aria-label'), '切换到黑夜模式');
    assert.equal(await app.evaluate(({ app }) => app.isPackaged), true);
    const appPath = await app.evaluate(({ app }) => app.getAppPath());
    assert.equal(fs.existsSync(path.join(appPath, '..', 'library', 'scripts', 'catalog.mjs')), true);
    assert.equal(fs.existsSync(path.join(appPath, '..', 'app-update.yml')), true, 'Missing packaged update provider configuration');
    await page.locator('[data-view=updates]').click();
    await page.waitForFunction(() => document.querySelector('#update-current').textContent.startsWith('v'));
    assert.equal(await page.locator('#update-check').isEnabled(), true);
    await page.locator('[data-view=worker]').click();
    await page.locator('#pair-worker [name=server]').fill(server);
    await page.locator('#pair-worker [name=key]').fill(pairing.key);
    await page.locator('#pair-worker button[type=submit]').click();
    await until(() => manager.snapshot().paired);
    await page.locator('[data-action=start]').click();
    await until(() => manager.snapshot().online);
    const task = await api(owner, '/api/tasks', 'POST', { content: '合成打包验收资料', submissionId: randomBytes(16).toString('hex') });
    await until(async () => (await api(owner, '/api/state')).tasks.some(item => item.id === task.id && item.state === 'completed'));
    await page.locator('[data-action=drain]').click();
    await until(() => !manager.snapshot().running);
    await page.locator('[data-view=overview]').click();
    await page.locator('#owner-pair [name=server]').fill(server);
    await page.locator('#owner-pair [name=key]').fill(key);
    await page.locator('#owner-pair button[type=submit]').click();
    await page.locator('#overview-data').waitFor({ state: 'visible' });
    await page.locator('[data-view=library]').click();
    await page.locator('#remote-entries [data-entry]').first().click();
    await page.waitForFunction(() => document.querySelector('#reader-paper')?.textContent?.includes('测试报告'));
    console.log('Packaged Worker, owner pairing, authenticated reader and resources: passed');
  } finally { await app.evaluate(({ app }) => app.quit()); await app.close(); await service.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });

