const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');

async function main() {
  const { createService } = await import('../src/server.mjs');
  const { api, processTask } = await import('../src/worker.mjs');
  const { detectAgents } = await import('../src/agents.mjs');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'collector-ui-'));
  const key = require('node:crypto').randomBytes(32).toString('hex');
  const app = createService({ dataDir: root, masterKey: key });
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const server = `http://127.0.0.1:${app.server.address().port}`;
  const owner = { server, ...(await api({ server }, '/api/pair', 'POST', { key, name: '测试管理端' })) };
  const pairing = await api(owner, '/api/pairings', 'POST', { role: 'worker' });
  const worker = { server, ...(await api({ server }, '/api/pair', 'POST', { key: pairing.key, name: 'Windows 工作站' })) };
  await api(worker, '/api/heartbeat', 'POST', { capabilities: ['article', 'webpage'], agents: ['codex'], platform: 'win32' });
  const task = await api(owner, '/api/tasks', 'POST', { url: 'https://example.com/fixture', type: 'article', autoArchive: false, tags: ['界面'], submissionId: 'ui-fixture' });
  await api(worker, '/api/claim', 'POST', {});
  const fixture = path.resolve(__dirname, '../test/fixtures/fake-agent.mjs');
  const agents = { codex: { command: process.execPath, args: [fixture], versionArgs: [fixture, '--version'] }, codebuddy: { enabled: false } };
  await processTask({ ...worker, agents, dataDir: path.join(root, 'worker') }, task, await detectAgents(agents));
  const output = path.resolve(__dirname, '../test-output/ui');
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 950 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(server);
    await page.locator('#login-form input[name=name]').fill('浏览器测试');
    await page.locator('#login-form input[name=key]').fill(key);
    await page.locator('#login-form button').click();
    await page.locator('#app').waitFor({ state: 'visible' });
    await page.locator('#new-task').click();
    await page.locator('#task-form textarea[name=content]').fill('【前端狂喜！超过7000个UI组件直接免费开源！-哔哩哔哩】 https://b23.tv/Xrtm87o\n分析一下这个视频的内容');
    await page.locator('#task-form input[name=tags]').fill('前端，组件');
    await page.locator('#task-form input[name=autoArchive]').uncheck();
    await page.locator('#dispatch-device').selectOption(worker.device.id);
    await page.locator('#task-form button[type=submit]').click();
    await page.locator('#task-dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#tasks .row').count(), 2);
    await page.screenshot({ path: path.join(output, 'desktop-tasks.png') });
    await page.locator('#tasks [data-task]').first().click();
    assert.ok((await page.locator('#task-detail').innerText()).includes('等待可用电脑'));
    assert.ok((await page.locator('#task-detail .task-content').innerText()).includes('分析一下这个视频的内容'));
    await page.locator('#detail-dialog [data-close]').click();
    page.on('dialog', dialog => dialog.accept());
    await page.locator(`[data-task="${task.id}"]`).click();
    await page.locator('[data-preview]').click();
    await page.locator('#reader').waitFor({ state: 'visible' });
    assert.ok((await page.locator('#document').innerText()).includes('这是测试报告'));
    await page.locator('#reader [data-close]').click();
    await page.locator(`[data-task="${task.id}"]`).click();
    await page.locator('[data-approve]').click();
    await page.locator('#detail-dialog').waitFor({ state: 'hidden' });
    await page.locator('[data-view=devices]').click();
    await page.locator('#pair-device').click();
    assert.equal(await page.locator('#pair-form select').count(), 0);
    await page.locator('#pair-form button').click();
    await page.locator('#pair-result').waitFor({ state: 'visible' });
    assert.ok((await page.locator('#pair-key').inputValue()).length >= 32);
    await page.locator('#pair-qr').evaluate(img => img.decode());
    assert.equal(await page.locator('#pair-qr').evaluate(img => img.naturalWidth > 0), true);
    await page.screenshot({ path: path.join(output, 'desktop-universal-pairing.png') });
    await page.locator('#pair-dialog [data-close]').click();
    await page.screenshot({ path: path.join(output, 'desktop-devices.png') });
    await page.locator('[data-view=archives]').click();
    const library = page.frameLocator('#library-frame');
    await library.locator('#search').fill('synthetic');
    await library.locator('[data-open]').first().waitFor();
    assert.equal(await library.locator('[data-open]').count(), 1);
    await library.locator('#search').fill('missing-search-result');
    await library.locator('#empty').waitFor({ state: 'visible' });
    await library.locator('#clear-search').click();
    await library.locator('#sort').selectOption('oldest');
    await library.locator('#results img').first().evaluate(img => img.decode());
    assert.ok(await library.locator('#results img').first().evaluate(img => img.naturalWidth > 0));
    await library.locator('[data-open]').first().click();
    await library.locator('#reader').waitFor({ state: 'visible' });
    assert.ok((await library.locator('#reader-content').innerText()).includes('这是测试报告'));
    await library.locator('[data-tab=attachments]').click();
    assert.equal(await library.locator('.file-link').count(), 3);
    await library.locator('#reader-content img').first().evaluate(img => img.decode());
    const pendingDownload = page.waitForEvent('download');
    await library.locator('#directory-link').click();
    const download = await pendingDownload;
    assert.equal(download.suggestedFilename(), 'archive.json');
    await page.screenshot({ path: path.join(output, 'desktop-reader.png') });
    await library.locator('#close-reader').click();
    for (const width of [375, 320]) {
      await page.setViewportSize({ width, height: 812 });
      await page.locator('[data-view=tasks]').click();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.screenshot({ path: path.join(output, `mobile-${width}.png`) });
      await page.locator('#new-task').click();
      assert.ok(await page.locator('#task-dialog').evaluate(el => el.scrollWidth <= el.clientWidth));
      await page.locator('#task-dialog [data-close]').first().click();
      await page.locator('[data-view=archives]').click();
      await library.locator('[data-open]').first().click();
      await library.locator('#reader').waitFor({ state: 'visible' });
      assert.ok(await library.locator('#reader').evaluate(el => el.scrollWidth <= el.clientWidth));
      await library.locator('#close-reader').click();
    }
    await page.setViewportSize({ width: 1440, height: 950 });
    await library.locator('[data-open]').first().click();
    await library.locator('#delete-entry').click();
    await library.locator('#result-count').filter({ hasText: '0 条资料' }).waitFor();
    await library.locator('#open-trash').click();
    await library.locator('#trash-dialog').waitFor({ state: 'visible' });
    assert.ok((await library.locator('#trash-dialog').innerText()).includes('自动化闭环测试资料'));
    await library.locator('#trash-dialog .button').click();
    await library.locator('[data-open]').first().waitFor();
    await page.locator('[data-view=devices]').click();
    await page.locator(`[data-revoke="${worker.device.id}"]`).click();
    await page.locator(`[data-revoke="${worker.device.id}"]`).waitFor({ state: 'hidden' });
    await assert.rejects(api(worker, '/api/heartbeat', 'POST', { capabilities: [], agents: [] }), { status: 401 });
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ result: 'passed', screenshots: output, checks: ['login', 'submit task', 'task events', 'pair devices', 'revoke worker', 'read archive', 'download', 'desktop and 320/375px mobile'] }, null, 2));
  } finally { await browser.close(); await app.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
