apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: library-app-info-pages
    files:
      - privacy.html
      - support.html
      - server.mjs
resources:
  - service.yaml
