const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../../..');
const assets=path.join(root,'collector/mobile/android/app/src/main/assets/mobile');
const output=path.join(root,'collector/mobile/test-output/emulator');fs.mkdirSync(output,{recursive:true});
const source=process.env.READER_BUNDLES||path.join(root,'collector/worker-data/prod-import/bundles');
const data={entries:[],documents:{}},files=new Map();
for(const name of fs.readdirSync(source)){const b=JSON.parse(fs.readFileSync(path.join(source,name)));const id=name.slice(0,-5),directory='files/'+id;const ef=b.files.map(f=>{const p=directory+'/'+f.path;files.set('/library/'+p,Buffer.from(f.body,'base64'));if(/\.(md|markdown|txt|srt|vtt)$/i.test(f.path))data.documents[p]=Buffer.from(f.body,'base64').toString();return {path:p,name:path.posix.basename(f.path),role:f.role,bytes:f.bytes};});const images=ef.filter(f=>/\.(png|jpe?g|webp)$/i.test(f.path));data.entries.push({...b.meta,archiveId:id,directory,files:ef,thumbnail:(images.find(f=>/cover|frame_003/i.test(f.name))||images[0])?.path,omitted:b.omitted});}
const server=http.createServer((req,res)=>{const p=decodeURIComponent(req.url.split('?')[0]);if(p==='/library/data'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));return;}if(files.has(p)){res.setHeader('Content-Type',p.endsWith('.png')?'image/png':'image/jpeg');res.end(files.get(p));return;}const name=p.replace('/library/mobile/','');if(!/^(index\.html|mobile\.(css|js)|icons\/(library|collect|person|bookmark|scan|update)\.png|vendor\/(marked|purify|lucide)\.js)$/.test(name)){res.writeHead(404).end();return;}res.setHeader('Content-Type',name.endsWith('.png')?'image/png':name.endsWith('.css')?'text/css':name.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(path.join(assets,name)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;
const results=[];for(const width of [360,393,412,780]){await page.setViewportSize({width,height:844});await page.goto(origin+'/library/mobile/index.html');await page.locator('.entry').first().waitFor();assert.equal(await page.locator('.entry').count(),data.entries.length);for(const theme of ['light','dark']){await page.evaluate(t=>window.NookTheme(t,t==='dark'),theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(output,`library-${width}-${theme}.png`)});await page.locator('[data-entry="video:BV1r2ey6EEh5"]').click();await page.locator('#reader:not([hidden])').waitFor();assert.ok((await page.locator('#document').innerText()).length>1000);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(output,`reader-${width}-${theme}.png`)});await page.locator('#back').click();await page.locator('#library:not([hidden])').waitFor();results.push({width,theme,overflow:false});}}
await page.setViewportSize({width:393,height:844});await page.locator('#query').fill('KVMem');assert.equal(await page.locator('.entry').count(),1);await page.locator('.entry-open').click();await page.locator('#save').click();await page.locator('#attachments').click();await page.locator('#details:not([hidden])').waitFor();await page.locator('#details-back').click();await page.locator('#reader:not([hidden])').waitFor();await page.locator('#back').click();assert.equal(await page.locator('#query').inputValue(),'KVMem');await page.locator('#clear').click();await page.locator('#favorites').click();assert.equal(await page.locator('.entry').count(),1);await page.reload();await page.locator('.entry').first().waitFor();await page.locator('#favorites').click();assert.equal(await page.locator('.entry').count(),1);await page.locator('#filter').click();await page.locator('#type').selectOption('article');await page.locator('#apply').click();assert.equal(await page.locator('.entry').count(),0);
await page.route('**/library/data',r=>r.fulfill({status:503,body:'unavailable'}));await page.reload();await page.locator('#message:not([hidden])').waitFor();assert.ok((await page.locator('#message').innerText()).includes('重试'));assert.equal(await page.locator('.entry').count(),0);await page.unroute('**/library/data');await page.locator('#refresh').click();await page.locator('.entry').first().waitFor();
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'web-checks.json'),JSON.stringify({results,search:true,favoritesPersisted:true,navigation:true,errors},null,2));console.log(JSON.stringify({layouts:results.length,search:true,favoritesPersisted:true,navigation:true,errors}));
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
