(() => {
  'use strict';
  const $=s=>document.querySelector(s),store=window.captureStore,bridge=window.captureBridge;
  const esc=v=>String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID(),date=v=>new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
  let detailSignature='';
  const supported=new Set(['image/jpeg','image/png','image/webp','image/gif','audio/mp4','audio/aac','audio/mpeg','audio/wav','audio/x-wav','audio/webm','audio/ogg','audio/flac']);
  let status={paired:false,server:''},items=[],draft={id:'draft',recordId:uid(),text:'',attachments:[]},selected=null,filter='all',page='record',saving=Promise.resolve(),flushing=false,refreshing=false,sending=false,recording=null,cameraStream=null,toastTimer,urls=[];
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
  function enqueue(work){const operation=saving.then(work);saving=operation.catch(error=>{toast('本机保存失败：'+error.message);$('#draft-status').textContent='保存失败，请保留当前窗口后重试';});return operation;}
  function saveDraft(){draft.text=$('#record-text').value;const snapshot=structuredClone(draft);return enqueue(async()=>{await store.put(snapshot);$('#draft-status').textContent='已保存在本机';});}
  const sha=async blob=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(v=>v.toString(16).padStart(2,'0')).join('');
  const baseMime=mime=>mime.split(';')[0];
  async function api(route,method='GET',json,blob,mime,server=status.server){
    const input={route,method,server,...(json===undefined?{}:{json}),...(blob?{bytes:await bridge.base64(blob),mime}: {})};
    const reply=await bridge.call('request',input);
    if(reply.status<200 || reply.status>=300)throw Object.assign(new Error(reply.json?.error || `服务请求失败（${reply.status}）`),{status:reply.status});
    return reply.json ?? bridge.blob(reply.bytes,reply.mime);
  }
  async function updateStatus(){try{status=await bridge.call('status');if(status.theme)document.documentElement.dataset.theme=status.theme;$('#connection-label').textContent=status.paired?'已连接':'本机记录';}catch{status={paired:false,server:''};$('#connection-label').textContent='连接不可用';}}
  function newUrls(){urls.forEach(URL.revokeObjectURL);urls=[];}
  function objectUrl(blob){const url=URL.createObjectURL(blob);urls.push(url);return url;}
  function updateSend(){for(const id of ['add-content','voice','camera','pick-photos','pick-audio'])$('#'+id).disabled=sending;$('#send').disabled=sending||Boolean(recording)||(!$('#record-text').value.trim()&&!draft.attachments.length);}
  function resize(){const input=$('#record-text');input.style.height='auto';input.style.height=Math.min(Math.max(100,input.scrollHeight),Math.max(150,innerHeight*.32))+'px';}
  function renderDraft(){newUrls();$('#attachments').innerHTML=draft.attachments.map(a=>`<div class="attachment">${a.mime.startsWith('image/')?`<img src="${objectUrl(a.thumbnail?.blob || a.blob)}" alt="${esc(a.name)}">`:`<span>录音</span>`}<span>${esc(a.name)}</span><button type="button" class="remove" data-remove="${a.id}" aria-label="删除附件">×</button></div>`).join('');updateSend();}
  function stateFor(item){if(item.sync==='conflict')return '版本冲突';if(item.sync==='failed')return '同步失败';if(item.sync==='syncing')return '同步中';if(item.sync==='pending')return '待同步';if(item.pendingProcess)return '加工待提交';if(item.tasks?.some(t=>t.state==='awaiting_review'))return '待确认';if(item.tasks?.some(t=>['queued','assigned','running','uploading'].includes(t.state)))return '加工中';if(item.tasks?.some(t=>t.state==='completed'))return '已归档';return '未加工';}
  const title=item=>item.text.trim().split('\n')[0] || (item.attachments.some(a=>a.mime.startsWith('image/'))?'一条照片记录':'一条语音记录');
  function row(item){return `<button class="record-row" data-open="${item.id}"><span class="row-content"><span class="row-title">${esc(title(item))}</span><span class="row-meta">${date(item.createdAt)} · ${item.attachments.length} 个附件 · ${item.server && item.server!==status.server?'其他资料空间':item.sync==='synced'?'已同步':'本机保留'}</span></span><span class="status">${stateFor(item)}</span></button>`;}
  function renderLists(){const sorted=items.toSorted((a,b)=>b.createdAt.localeCompare(a.createdAt));$('.recent').hidden=!sorted.length;$('#recent-list').innerHTML=sorted.slice(0,3).map(row).join('')||'';$('#inbox-list').innerHTML=sorted.filter(item=>filter==='all'||filter==='pending'&&item.sync!=='synced'||filter==='unprocessed'&&!item.tasks?.length||filter==='review'&&item.tasks?.some(t=>t.state==='awaiting_review')).map(row).join('')||'<p class="empty">这里暂时没有记录。</p>';}
  function navigate(target){page=target;document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==target+'-screen');$('#page-title').textContent={record:'记录',inbox:'收件箱',detail:'记录详情'}[target];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===target));renderLists();if(target==='detail')void renderDetail();window.scrollTo(0,0);}
  window.captureNavigate=navigate;
  async function reloadItems(){items=(await store.all()).filter(item=>item.id!=='draft');renderLists();}
  async function refresh(){if(refreshing)return;refreshing=true;try{await updateStatus();if(!status.paired)return;const identity=status.server,data=await api('/api/records');if(status.server!==identity)return;
    for(const remote of data.records){const existing=await store.get(remote.id);if(existing && existing.sync!=='synced')continue;await store.put({...existing,...remote,server:identity,sync:'synced',remoteVersion:remote.version,attachments:remote.attachments.map(a=>({...a,blob:existing?.attachments.find(old=>old.sha256===a.sha256)?.blob}))});}
    await reloadItems();$('#inbox-notice').textContent='';if(page==='detail')await fetchDetail();
  }catch(error){$('#inbox-notice').textContent='无法刷新远端，本机记录仍可用：'+error.message;}finally{refreshing=false;}}
  async function fetchDetail(){const id=selected,item=items.find(i=>i.id===id);if(!item||item.sync!=='synced'||item.server!==status.server)return;try{const remote=await api('/api/records/'+id);const latest=await store.get(id);if(selected!==id||latest.sync!=='synced')return;await store.put({...latest,tasks:remote.tasks});await reloadItems();await renderDetail();}catch(error){$('#detail-error').textContent=error.message;}}
  async function thumbnail(blob,mime){if(!mime.startsWith('image/'))return null;const source=URL.createObjectURL(blob);try{const image=new Image();image.src=source;await image.decode();const scale=Math.min(1,480/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const preview=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.78));return preview?{blob:preview,mime:'image/jpeg',sha256:await sha(preview),bytes:preview.size}:null;}catch{return null;}finally{URL.revokeObjectURL(source);}}
  async function addFiles(files){for(const file of files){const mime=baseMime(file.type || '');if(!supported.has(mime))throw new Error('暂不支持该格式，请选择 JPG、PNG、WebP、GIF 或常见音频');if(file.size>32*1024*1024)throw new Error('单个附件不能超过 32 MiB');if(draft.attachments.length>=20)throw new Error('每条记录最多 20 个附件');const blob=file.slice(0,file.size,mime);draft.attachments.push({id:file.captureId || uid(),name:file.name.slice(0,200),mime,blob,bytes:file.size,sha256:await sha(blob),thumbnail:await thumbnail(blob,mime)});await saveDraft();renderDraft();}}
  async function nativeFile(file){const known=draft.attachments.some(a=>a.id===file.id)||items.some(item=>item.attachments.some(a=>a.id===file.id));if(!known){const input=new File([bridge.blob(file.bytes,file.mime)],file.name,{type:file.mime});input.captureId=file.id;await addFiles([input]);}await bridge.call('mediaAck',file.id);}
  async function flush(){if(flushing)return;flushing=true;try{await updateStatus();if(!status.paired)return;let pending=(await store.all()).filter(i=>i.id!=='draft' && ['pending','failed','syncing'].includes(i.sync));
    for(const item of pending){if(item.server && item.server!==status.server)continue;item.server ||= status.server;item.sync='syncing';await store.put(item);await reloadItems();if(page==='detail')await renderDetail();
      try{for(const a of item.attachments){if(a.thumbnail?.blob){const preview=await api('/api/records/media/'+a.thumbnail.sha256,'PUT',undefined,a.thumbnail.blob,a.thumbnail.mime,item.server);if(preview.sha256!==a.thumbnail.sha256||preview.bytes!==a.thumbnail.bytes)throw new Error('缩略图校验失败');}if(!a.blob)continue;const uploaded=await api('/api/records/media/'+a.sha256,'PUT',undefined,a.blob,a.mime,item.server);if(uploaded.sha256!==a.sha256||uploaded.bytes!==a.bytes)throw new Error('服务端未确认附件完整性');}
        const payload=item.payload || {requestId:uid(),baseVersion:item.remoteVersion||0,text:item.text,createdAt:item.createdAt,attachments:item.attachments.map(({id,name,sha256,thumbnail,thumbnailSha256})=>({id,name,sha256,...(thumbnail?.sha256||thumbnailSha256?{thumbnailSha256:thumbnail?.sha256||thumbnailSha256}:{})}))};item.payload=payload;await store.put(item);
        const remote=await api('/api/records/'+item.id,'PUT',payload,undefined,undefined,item.server);if(remote.id!==item.id||remote.version!==payload.baseVersion+1)throw new Error('服务端未确认记录版本');item.sync='synced';item.remoteVersion=remote.version;item.version=remote.version;item.error='';delete item.payload;
      }catch(error){item.sync=error.status===409?'conflict':'failed';item.error=error.message;}await store.put(item);}
    for(const item of (await store.all()).filter(i=>i.pendingProcess && i.sync==='synced' && i.server===status.server)){try{const task=await api('/api/records/'+item.id+'/process','POST',item.pendingProcess,undefined,undefined,item.server);item.tasks=[task,...(item.tasks||[])];delete item.pendingProcess;item.error='';}catch(error){item.error=error.message;}await store.put(item);}
    await reloadItems();if(page==='detail')await renderDetail();
  }finally{flushing=false;}}
  async function mediaBlob(item,a){if(a.blob)return a.blob;const blob=await api('/api/records/media/'+a.sha256,'GET',undefined,undefined,undefined,item.server);if(await sha(blob)!==a.sha256)throw new Error('附件校验失败');return blob;}
  async function renderDetail(){const item=items.find(i=>i.id===selected);if(!item)return;const signature=JSON.stringify([item.id,item.version,item.text,item.sync,item.error,item.pendingProcess,item.tasks,status.server]);if(signature===detailSignature)return;detailSignature=signature;$('#detail-title').textContent=title(item);$('#detail-date').textContent=date(item.createdAt)+' · 第 '+(item.version||1)+' 版';$('#detail-state').textContent=stateFor(item);$('#detail-body').textContent=item.text;$('#detail-error').textContent=item.error||'';$('#retry-sync').hidden=item.sync==='synced'&&!item.pendingProcess;$('#resolve-conflict').hidden=item.sync!=='conflict';$('#process').disabled=item.sync!=='synced'||Boolean(item.pendingProcess)||item.server!==status.server;
    $('#detail-media').innerHTML=item.attachments.map(a=>`<div class="media-card"><span>${esc(a.name)}</span><button data-media="${a.id}">查看 / 播放</button><div id="media-${a.id}"></div></div>`).join('');
    $('#result-section').innerHTML=(item.tasks||[]).map(t=>`<div class="result"><p class="result-label">第 ${t.recordVersion} 版 · ${esc(t.events?.at(-1)?.message||t.state)}</p><button data-task="${t.id}">查看加工任务</button>${t.state==='awaiting_review'?`<button data-preview="${t.id}">预览加工结果</button><div id="preview-${t.id}"></div>`:''}</div>`).join('');}
  $('#record-text').addEventListener('input',()=>{resize();updateSend();void saveDraft();});
  $('#composer').addEventListener('submit',async event=>{event.preventDefault();if($('#send').disabled)return;sending=true;$('#record-text').disabled=true;updateSend();try{await saveDraft();await saving;await updateStatus();const previous=draft.editingId?await store.get(draft.editingId):null;if(previous?.sync==='syncing')throw new Error('正在同步，请稍后补充');
    const item={...previous,id:draft.editingId||draft.recordId,text:draft.text,attachments:structuredClone(draft.attachments),createdAt:previous?.createdAt||new Date().toISOString(),version:previous?.version||1,remoteVersion:previous?.remoteVersion||0,server:previous?.server||status.server||null,sync:'pending',error:''};delete item.payload;
    await store.put(item);selected=item.id;draft={id:'draft',recordId:uid(),text:'',attachments:[]};await store.put(draft);$('#record-text').value='';renderDraft();resize();await reloadItems();navigate('detail');toast('已保存在本机，正在同步到收件箱');void flush();
  }catch(error){toast(error.message);}finally{sending=false;$('#record-text').disabled=false;updateSend();}});
  $('#add-content').onclick=()=>$('#add-menu').hidden=!$('#add-menu').hidden;
  for(const [button,input] of [['pick-photos','photo-input'],['pick-audio','audio-input']]){$('#'+button).onclick=()=>{$('#add-menu').hidden=true;$('#'+input).click();};$('#'+input).onchange=event=>{void addFiles(event.target.files).catch(error=>toast(error.message));event.target.value='';};}
  $('#composer').ondragover=event=>event.preventDefault();$('#composer').ondrop=event=>{event.preventDefault();void addFiles(event.dataTransfer.files).catch(error=>toast(error.message));};
  $('#voice').onclick=async()=>{try{if(recording)return finishRecording();await updateStatus();if(status.nativeMedia){await bridge.call('recordStart');recording={native:true};}else{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm','audio/mp4','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m));const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{}),chunks=[],attachmentId=uid();
      recorder.ondataavailable=event=>{if(!event.data.size)return;chunks.push(event.data);const blob=new Blob(chunks,{type:baseMime(recorder.mimeType)});void enqueue(async()=>{const a={id:attachmentId,name:'录音-'+new Date().toISOString().replace(/[:.]/g,'-'),mime:blob.type,blob,bytes:blob.size,sha256:await sha(blob)};draft.attachments=draft.attachments.filter(old=>old.id!==attachmentId);draft.attachments.push(a);await store.put(structuredClone(draft));renderDraft();}).catch(error=>toast(error.message));};recorder.onstop=()=>stream.getTracks().forEach(t=>t.stop());recorder.start(1000);recording={recorder,stream};}
    recording.started=Date.now();recording.timer=setInterval(()=>{const seconds=Math.floor((Date.now()-recording.started)/1000);$('#recording-time').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');},250);$('#recording-bar').hidden=false;updateSend();
  }catch(error){toast('录音不可用：'+error.message+'。可以继续输入文字或导入音频。');}};
  async function finishRecording(){if(!recording)return;const session=recording;clearInterval(session.timer);$('#recording-bar').hidden=true;try{if(session.native){const result=await bridge.call('recordStop');for(const file of result.files||[])await nativeFile(file);}else if(session.recorder.state!=='inactive'){await new Promise(resolve=>{session.recorder.addEventListener('stop',resolve,{once:true});session.recorder.stop();});await saving;}}catch(error){toast(error.message);}finally{recording=null;updateSend();}}
  $('#finish-recording').onclick=finishRecording;
  $('#camera').onclick=async()=>{try{await updateStatus();if(status.nativeMedia){const file=await bridge.call('photo');if(file)await nativeFile(file);return;}cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('#camera-preview').srcObject=cameraStream;$('#camera-dialog').showModal();}catch(error){toast('相机不可用：'+error.message+'。可以从图片中选择。');$('#photo-input').click();}};
  $('#take-photo').onclick=()=>{const video=$('#camera-preview'),canvas=document.createElement('canvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>{if(blob)void addFiles([new File([blob],'照片-'+Date.now()+'.jpg',{type:'image/jpeg'})]);},'image/jpeg',.9);$('#camera-dialog').close();};
  $('#camera-dialog').addEventListener('close',()=>{cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;});
  document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  $('#retry-sync').onclick=()=>void flush();$('#refresh').onclick=()=>void refresh().then(flush);
  $('#connect').onclick=()=>bridge.call('navigate','settings');
  $('#edit-record').onclick=async()=>{const item=items.find(i=>i.id===selected);if(item.sync!=='synced'){toast('请先完成同步，冲突时使用保留本机内容并重发');return;}try{const attachments=[];for(const a of item.attachments)attachments.push({...a,blob:await mediaBlob(item,a)});draft={id:'draft',recordId:item.id,editingId:item.id,text:item.text,attachments};$('#record-text').value=draft.text;await saveDraft();renderDraft();resize();navigate('record');}catch(error){toast(error.message);}};
  $('#resolve-conflict').onclick=async()=>{try{const item=items.find(i=>i.id===selected),remote=await api('/api/records/'+item.id,'GET',undefined,undefined,undefined,item.server);item.remoteVersion=remote.version;item.payload=null;item.sync='pending';await store.put(item);void flush();}catch(error){toast(error.message);}};
  $('#process').onclick=async()=>{try{const remote=await api('/api/state');$('#dispatch-device').innerHTML='<option value="">自动选择可用电脑</option>'+remote.devices.filter(d=>d.role==='worker'||d.category==='desktop').map(d=>`<option value="${esc(d.id)}">${esc(d.name)}${d.online?' · 在线':' · 离线'}</option>`).join('');}catch{}$('#process-error').textContent='';$('#process-dialog').showModal();};
  $('#process-form').onsubmit=async event=>{event.preventDefault();const item=await store.get(selected),preset=new FormData(event.target).get('preset'),instructions=$('#instructions').value.trim();if(preset==='custom'&&!instructions){$('#process-error').textContent='请填写自定义加工要求';return;}$('#start-process').disabled=true;try{item.pendingProcess ||= {requestId:uid(),baseVersion:item.remoteVersion,preset,instructions,deviceId:$('#dispatch-device').value||null,agent:$('#dispatch-agent').value||null};await store.put(item);$('#process-dialog').close();await flush();toast('加工请求已保存，连接可用时提交');}catch(error){$('#process-error').textContent=error.message;}finally{$('#start-process').disabled=false;}};
  document.addEventListener('click',async event=>{try{const nav=event.target.closest('[data-page]');if(nav)navigate(nav.dataset.page);const native=event.target.closest('[data-native]');if(native)await bridge.call('navigate',native.dataset.native);
    const remove=event.target.closest('[data-remove]');if(remove){draft.attachments=draft.attachments.filter(a=>a.id!==remove.dataset.remove);await saveDraft();renderDraft();}
    const open=event.target.closest('[data-open]');if(open){selected=open.dataset.open;navigate('detail');await fetchDetail();}
    const filtering=event.target.closest('[data-filter]');if(filtering){filter=filtering.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b===filtering));renderLists();}
    const media=event.target.closest('[data-media]');if(media){const item=items.find(i=>i.id===selected),a=item.attachments.find(a=>a.id===media.dataset.media),blob=await mediaBlob(item,a),host=$('#media-'+a.id);host.innerHTML='';const element=document.createElement(a.mime.startsWith('image/')?'img':'audio');element.src=objectUrl(blob);element.alt=a.name;element.controls=true;host.append(element);}
    const task=event.target.closest('[data-task]');if(task)await bridge.call('navigate','tasks');
    const preview=event.target.closest('[data-preview]');if(preview){const bundle=await api('/api/tasks/'+preview.dataset.preview+'/draft'),host=$('#preview-'+preview.dataset.preview);host.textContent='';for(const file of bundle.files.filter(f=>['summary','analysis'].includes(f.role))){const pre=document.createElement('pre');pre.className='result-copy';pre.textContent=new TextDecoder().decode(await bridge.blob(file.body,'text/plain').arrayBuffer());host.append(pre);}const button=document.createElement('button');button.textContent='确认归档';button.className='primary';button.onclick=async()=>{button.disabled=true;try{await api('/api/tasks/'+preview.dataset.preview+'/approve','POST',{});await fetchDetail();toast('已确认归档');}catch(error){button.disabled=false;toast(error.message);}};host.append(button);}
  }catch(error){toast(error.message);}});
  async function recoverNative(){if(status.nativeMedia){const recovered=await bridge.call('recover');for(const file of recovered.files||[])await nativeFile(file);}}
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording)void finishRecording();if(!document.hidden)void refresh().then(recoverNative).then(flush).catch(error=>toast(error.message));});
  addEventListener('online',()=>void refresh().then(flush));
  async function start(){try{draft=await store.get('draft')||draft;$('#record-text').value=draft.text;renderDraft();resize();await reloadItems();await updateStatus();if(status.nativeMedia){const recovered=await bridge.call('recover');for(const file of recovered.files||[])await nativeFile(file);}await refresh();await flush();}catch(error){toast(error.message);}setInterval(()=>{void refresh().then(flush);},10000);}
  if(new URLSearchParams(location.search).has('embedded'))document.body.classList.add('embedded');
  void start();
})();
